# Generated by Django 4.2.3 on 2023-07-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
